
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://innerjoin.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Lukas Steiger"
title: ">> Lukas Steiger <<"
description: "Personal blog and website of Lukas Steiger. All opinions expressed in this blog are mine and are not related to any institution or company im related to or blogging about."
keywords: ""
favicon: "/img/favicon.ico"
404-img: "/img/me.jpg"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 15
start-delay: 200
delete-delay: 6000
lines: # You can add HTML Tags in the Text
  - text: "To iterate is human, to recurse divine. - L. Peter Deutsch"
  - text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates"

me-img: "/img/me.jpg"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

# icon-36p: ""
# icon-48p: ""
# icon-72p: ""
# icon-96p: ""
# icon-144p: ""
# icon-192p: ""

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "innerjoin"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/hsr-campus.jpg"
    date: "September 2014 - Today"
    description: "Computer Science part-time studies @ <a target=\"_blank\" href=\"http://hsr.ch\">University of Applied Sciences Rapperswil</a> & part-time job as Software Engineer @ <a target=\"_blank\" href=\"http://siemens.ch/buildingtechnologies\">Siemens Building Technologies</a>"
  - image: "/img/timeline/siemens-parking.jpg"
    date: "August 2010 - August 2014"
    description: "Computer Science apprenticeship @ <a target=\"_blank\" href=\"http://siemens.ch/buildingtechnologies\">Siemens Building Technologies</a>"

# First image of the Timeline

timeline-img: "/img/timeline/me.jpg"

###########
# Contact #
###########

email: "your@email.here"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/innerjoin"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: ""

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
